[workspace]

members = [ "crates/*" ]

[workspace.package]
authors = ["Stephen Walker-Weinshenker"]
edition = "2021"
repository = "https://github.com/sww1235/connection-diagram-manager-rust"
license = "MIT OR Apache-2.0"
