[package]
name = "connection-diagram-manager-rust"
version = "0.1.0"
authors = ["Stephen Walker-Weinshenker"]
edition = "2021"
repository = "https://github.com/sww1235/connection-diagram-manager-rust"
description = "Connection Diagram Manager and visualizer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive", "unicode", "wrap_help"] }
log = "0.4.17"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
simple_logger = "4.0.0"
uom = "0.33.0"

[lib]
name = "cdm_core"
path = "src/lib.rs"

[[bin]]
name = "cdm_cli"
path = "src/bin/cli.rs"
