
# TODO: remove this. colored has a lower windows-sys version than
# chrono which is causing errors. need colored to update first
# to eliminate clippy spam
allowed-duplicate-crates = ["windows-targets", "windows_aarch64_gnullvm", "windows_aarch64_msvc", "windows_i686_gnu", "windows_i686_msvc", "windows_x86_64_gnu", "windows_x86_64_gnullvm", "windows_x86_64_msvc"]

doc-valid-idents = ["RPMale","RPFemale", ".."]
